stages:
  prepare:
    cmd: python src/prepare.py --input ./data/train_anomaly.csv --output ./data/prepare
    deps:
    - data/train_anomaly.csv
    - src/prepare.py
    outs:
    - data/prepare:
        cache: false
  train_lr:
    cmd: python src/train_ridge.py --input ./data/prepare/prepared_train.csv --output ./models/model_ridge.pkl
    deps:
    - data/prepare
    - src/train_ridge.py
    outs:
    - models/model_ridge.pkl:
        cache: false
  train_xgb:
    cmd: python src/train_xgb.py --input ./data/prepare/prepared_train.csv --output ./models/model_xgb.pkl
    deps:
    - data/prepare
    - src/train_xgb.py
    outs:
    - models/model_xgb.pkl:
        cache: false
  train_final:
    cmd: python src/final_model.py --models ./models/model_ridge.pkl ./models/model_xgb.pkl --input ./data/prepare/prepared_val.csv --output ./models/final_model.pkl
    deps:
      - data/prepare
      - models/model_xgb.pkl
      - models/model_ridge.pkl
      - src/final_model.py
    outs:
      - models/final_model.pkl:
          cache: false
  evaluate:
    cmd: python src/evaluate.py --input-data ./data/prepare/prepared_val.csv --input-model ./models/final_model.pkl --output ./scores.json
    deps:
    - data/prepare
    - models/final_model.pkl
    - src/evaluate.py
    metrics:
    - scores.json:
        cache: false
